sudo: false
language: go

go:
    - 1.9.x

install: true

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - cd docker
  - docker build -t hehety/godfs:latest .
  - docker push hehety/godfs